<a href="https://colab.research.google.com/github/chahat7414gupta/section-2/blob/main/section2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [5]:
import pandas as pd

# Read the data from the text file into a list of dictionaries
data = []
with open('section2_data.txt', 'r') as file:
    for line in file:
        data.append(eval(line))

# Convert the list of dictionaries into a DataFrame
my_data = pd.DataFrame(data)


# Print the DataFrame
print(my_data)

    _i          frame     video  value                labels
0    0  frame_000.png  video000     39                [bird]
1    1  frame_001.png  video000     33           [frog, dog]
2    2  frame_002.png  video000     25        [panda, panda]
3    3  frame_003.png  video000     28            [dog, dog]
4    4  frame_004.png  video000     16                 [cat]
5    5  frame_005.png  video000     32    [bird, frog, bird]
6    6  frame_006.png  video000     35           [bird, dog]
7    7  frame_000.png  video001     25           [dog, bird]
8    8  frame_001.png  video001     16    [dog, panda, bird]
9    9  frame_002.png  video001     23               [panda]
10  10  frame_003.png  video001      3     [bird, cat, bird]
11  11  frame_004.png  video001      8      [frog, cat, cat]
12  12  frame_005.png  video001      2      [frog, cat, dog]
13  13  frame_006.png  video001      0          [dog, panda]
14  14  frame_007.png  video001     26           [dog, bird]
15  15  frame_008.png  video001     38                [frog]
16  16  frame_009.png  video001     34                [frog]
17  17  frame_000.png  video002     40    [dog, frog, panda]
18  18  frame_001.png  video002     35  [bird, panda, panda]
19  19  frame_002.png  video002     23    [frog, frog, frog]
20  20  frame_003.png  video002     37      [dog, dog, bird]
21  21  frame_004.png  video002     14      [cat, dog, bird]
22  22  frame_000.png  video003     28                [bird]
23  23  frame_001.png  video003     26      [bird, dog, dog]
24  24  frame_002.png  video003      2       [cat, dog, dog]
25  25  frame_003.png  video003     24               [panda]
26  26  frame_004.png  video003     24     [cat, cat, panda]
27  27  frame_005.png  video003      5       [cat, cat, dog]
28  28  frame_006.png  video003     33                [frog]
29  29  frame_007.png  video003     26          [frog, bird]
30  30  frame_008.png  video003     41  [panda, panda, bird]
31  31  frame_009.png  video003     35      [dog, dog, frog]
32  32  frame_010.png  video003     39          [frog, bird]
33  33  frame_011.png  video003      6           [bird, cat]
34  34  frame_012.png  video003     23               [panda]
35  35  frame_013.png  video003      5               [panda]
36  36  frame_014.png  video003      4                [bird]
37  37  frame_015.png  video003     40     [dog, panda, cat]
38  38  frame_016.png  video003     20                [frog]
39  39  frame_017.png  video003     21          [dog, panda]
40  40  frame_000.png  video004     17                [frog]
41  41  frame_001.png  video004     26      [frog, dog, cat]
42  42  frame_002.png  video004     32    [panda, bird, cat]
43  43  frame_003.png  video004     31    [panda, cat, bird]
44  44  frame_004.png  video004     21                 [dog]
45  45  frame_005.png  video004      5               [panda]
46  46  frame_006.png  video004     29          [bird, bird]
47  47  frame_007.png  video004     41                [bird]
48  48  frame_008.png  video004     33               [panda]
49  49  frame_009.png  video004     14                [frog]
50  50  frame_010.png  video004      2                 [dog]

In [6]:
my_data = df.reset_index(drop=True)

In [7]:
my_data

    _i          frame     video  value                labels
0    0  frame_000.png  video000     39                [bird]
1    1  frame_001.png  video000     33           [frog, dog]
2    2  frame_002.png  video000     25        [panda, panda]
3    3  frame_003.png  video000     28            [dog, dog]
4    4  frame_004.png  video000     16                 [cat]
5    5  frame_005.png  video000     32    [bird, frog, bird]
6    6  frame_006.png  video000     35           [bird, dog]
7    7  frame_000.png  video001     25           [dog, bird]
8    8  frame_001.png  video001     16    [dog, panda, bird]
9    9  frame_002.png  video001     23               [panda]
10  10  frame_003.png  video001      3     [bird, cat, bird]
11  11  frame_004.png  video001      8      [frog, cat, cat]
12  12  frame_005.png  video001      2      [frog, cat, dog]
13  13  frame_006.png  video001      0          [dog, panda]
14  14  frame_007.png  video001     26           [dog, bird]
15  15  frame_008.png  video001     38                [frog]
16  16  frame_009.png  video001     34                [frog]
17  17  frame_000.png  video002     40    [dog, frog, panda]
18  18  frame_001.png  video002     35  [bird, panda, panda]
19  19  frame_002.png  video002     23    [frog, frog, frog]
20  20  frame_003.png  video002     37      [dog, dog, bird]
21  21  frame_004.png  video002     14      [cat, dog, bird]
22  22  frame_000.png  video003     28                [bird]
23  23  frame_001.png  video003     26      [bird, dog, dog]
24  24  frame_002.png  video003      2       [cat, dog, dog]
25  25  frame_003.png  video003     24               [panda]
26  26  frame_004.png  video003     24     [cat, cat, panda]
27  27  frame_005.png  video003      5       [cat, cat, dog]
28  28  frame_006.png  video003     33                [frog]
29  29  frame_007.png  video003     26          [frog, bird]
30  30  frame_008.png  video003     41  [panda, panda, bird]
31  31  frame_009.png  video003     35      [dog, dog, frog]
32  32  frame_010.png  video003     39          [frog, bird]
33  33  frame_011.png  video003      6           [bird, cat]
34  34  frame_012.png  video003     23               [panda]
35  35  frame_013.png  video003      5               [panda]
36  36  frame_014.png  video003      4                [bird]
37  37  frame_015.png  video003     40     [dog, panda, cat]
38  38  frame_016.png  video003     20                [frog]
39  39  frame_017.png  video003     21          [dog, panda]
40  40  frame_000.png  video004     17                [frog]
41  41  frame_001.png  video004     26      [frog, dog, cat]
42  42  frame_002.png  video004     32    [panda, bird, cat]
43  43  frame_003.png  video004     31    [panda, cat, bird]
44  44  frame_004.png  video004     21                 [dog]
45  45  frame_005.png  video004      5               [panda]
46  46  frame_006.png  video004     29          [bird, bird]
47  47  frame_007.png  video004     41                [bird]
48  48  frame_008.png  video004     33               [panda]
49  49  frame_009.png  video004     14                [frog]
50  50  frame_010.png  video004      2                 [dog]

In [8]:
print(type(my_data))

<class 'pandas.core.frame.DataFrame'>

In [10]:
df = pd.DataFrame(my_data)

# Write the DataFrame to a CSV file
df.to_csv('my_data.csv', index=False)

In [12]:
import csv

# Open the CSV file for reading
with open('my_data.csv', mode='r') as file:

    # Create a CSV reader object
    reader = csv.reader(file)

    # Calculate the number of rows in the file (excluding header)
    num_rows = len(list(reader)) - 1

    # Print the number of rows
    print(f'The CSV file has {num_rows} rows (excluding header).')

    # Rewind to the beginning of the file
    file.seek(0)

    # Skip the header row
    next(reader)

    # Iterate over the rows in the file
    for i, row in enumerate(reader):

        # Check if this is the 26th or 43rd row
        if i == 25:
            print(f'The 26th row is: {row}')
        elif i == 42:
            print(f'The 43rd row is: {row}')

The CSV file has 51 rows (excluding header).
The 26th row is: ['25', 'frame_003.png', 'video003', '24', "['panda']"]
The 43rd row is: ['42', 'frame_002.png', 'video004', '32', "['panda', 'bird', 'cat']"]

In [13]:
def video_frame_count(my_data):
    # Group the DataFrame by 'video' and count the number of occurrences of each group
    video_counts = my_data.groupby('video').size()
    
    # Convert the resulting Pandas Series to a dictionary
    video_dict = dict(video_counts)
    
    return video_dict

In [14]:
my_dict = video_frame_count(my_data)
print(my_dict)

{'video000': 7, 'video001': 10, 'video002': 5, 'video003': 18, 'video004': 11}

In [21]:
def generate_dog_counts(my_data):
    dog_counts = {}
    for i in range(len(my_data)):
        if 'dog' in my_data.loc[i, 'labels']:
            video_name = my_data.loc[i, 'video']
            value = my_data.loc[i, 'value']
            if video_name not in dog_counts:
                dog_counts[video_name] = 0
            dog_counts[video_name] += value
    return dog_counts

In [23]:
my_dicte=generate_dog_counts(my_data)
print(my_dicte)

{'video000': 96, 'video001': 69, 'video002': 91, 'video003': 129, 'video004': 49}

In [24]:
def animal_counts(my_data):
    animal_counts = {}
    for index, row in my_data.iterrows():
        if row['video'] == 'video003' or row['value'] % 2 != 0:
            continue
        for animal in row['labels']:
            if animal in animal_counts:
                animal_counts[animal] += 1
            else:
                animal_counts[animal] = 1
    return animal_counts

In [25]:
my_dic=animal_counts(my_data)
print(my_dic)

{'dog': 10, 'cat': 7, 'bird': 6, 'frog': 8, 'panda': 4}